<?php
// echo "<pre>";
require_once 'C:\xampp\htdocs\mvcrevised\View\html\header.phtml';
$product = $this->getData();
?>

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>edit prodcut</title>
</head>
<body>
	<form action="index.php?c=product&a=save&id=<?php echo $product->product_id ?>" method="POST">
		<div class="row mt-3">
			<div class="col-3">
				<h3>EDIT PRODUCT</h3>
			</div>
			<div class="col-3">
				<button class="btn btn-primary">save</button>
			</div>
		</div>
		

		<table>
			<tr>
				<td>product_id :</td>
				<td>
					<input type="text" name="product[product_id]" value="<?php echo $product->product_id; ?>">
				</td>
			</tr>
			<tr>
				<td>Name :</td>
				<td>
					<input type="text" name="product[name]" value="<?php echo $product->name; ?>">
				</td>
			</tr>
			<tr>
				<td>Sku :</td>
				<td>
					<input type="text" name="product[sku]" value="<?php echo $product->sku; ?>">
				</td>
			</tr>
			<tr>
				<td>Cost :</td>
				<td>
					<input type="text" name="product[cost]" value="<?php echo $product->cost; ?>">
				</td>
			</tr>
			<tr>
				<td>Price :</td>
				<td>
					<input type="text" name="product[price]" value="<?php echo $product->price; ?>">
				</td>
			</tr>
			<tr>
				<td>Quantity :</td>
				<td>
					<input type="text" name="product[quantity]" value="<?php echo $product->quantity; ?>">
				</td>
			</tr>
			<tr>
				<td>Description :</td>
				<td>
					<input type="text" name="product[description]" value="<?php echo $product->description; ?>">
				</td>
			</tr>
			<tr>
					<td> Status</td>
					<td> <select name="product[status]" >
						<?php foreach ($product->getTable()->getStatusOptions() as $key => $value): ?>
						<option value="<?php echo $key ?>"><?php echo $value ?></option>
						<?php endforeach; ?>
						
					</select> </td>
				</tr>
			<tr>
				<td>Color :</td>
				<td>
					<input type="text" name="product[color]" value="<?php echo $product->color; ?>">
				</td>
			</tr>
			<tr>
				<td>Material :</td>
				<td>
					<input type="text" name="product[material]" value="<?php echo $product->material; ?>">
				</td>
			</tr>
			
		</table>


		
	</form>

</body>
</html>