<?php
// echo "<pre>";
require_once 'C:\xampp\htdocs\mvcrevised\View\html\header.phtml';
$customer = $this->getData('Customer');
$address = $this->getData('CustomerAddress');
?>

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>edit Customer</title>
</head>
<body>
	<form action="index.php?c=customer&a=save&id=<?php echo $customer->customer_id ?>" method="POST">
		<div class="row mt-3">
			<div class="col-3">
				<h3>EDIT CUSTOMER</h3>
			</div>
			<div class="col-3">
				<button class="btn btn-primary">save</button>
			</div>
		</div>
		

		<table>
			<tr>
				<td>FirstName :</td>
				<td>
					<input type="text" name="customer[fname]" value="<?php echo $customer->fname; ?>">
				</td>
			</tr>
			<tr>
				<td>LastName :</td>
				<td>
					<input type="text" name="customer[lname]" value="<?php echo $customer->lname; ?>">
				</td>
			</tr>
			<tr>
				<td>Email :</td>
				<td>
					<input type="text" name="customer[email]" value="<?php echo $customer->email; ?>">
				</td>
			</tr>
			<tr>
				<td>Gender :</td>
				<td>
					<input type="text" name="customer[gender]" value="<?php echo $customer->gender; ?>">
				</td>
			</tr>
			<tr>
				<td>Mobile :</td>
				<td>
					<input type="text" name="customer[mobile]" value="<?php echo $customer->mobile; ?>">
				</td>
			</tr>
			
			
			<tr>
					<td> Status</td>
					<td> <select name="customer[status]" >
						<?php foreach ($customer->getTable()->getStatusOptions() as $key => $value): ?>
						<option value="<?php echo $key ?>"><?php echo $value ?></option>
						<?php endforeach; ?>
						
					</select> </td>
				</tr>
			
		</table>
			
			

		<table>
			<h3>CUSTOMER ADDRESS</h3>
			<div class="mt-3"></div>
			<tr>
				<td>AddressId :</td>
				<td>
					<input type="text" name="address[address_id]" value="<?php echo $address->address_id ?>"></td>
			</tr>
			<tr>
				<td>Address :</td>
				<td>
					<input type="text" name="address[address]" value="<?php echo $address->address ?>"></td>
			</tr>
			<tr>
				<td>City :</td>
				<td>
					<input type="text" name="address[city]" value="<?php echo $address->city ?>"></td>
			</tr>
			<tr>
				<td>Satte :</td>
				<td>
					<input type="text" name="address[state]" value="<?php echo $address->state ?>">	</td>
			</tr>
			<tr>
				<td>Country :</td>
				<td>
					<input type="text" name="address[country]" value="<?php echo $address->country ?>"	>	</td>
			</tr>
			<tr>
				<td>ZipCode :</td>
				<td>
					<input type="text" name="address[zip_code]" value="<?php echo $address->zip_code ?>"></td>
			</tr>
			
		</table>




		
	</form>

</body>
</html>