
		<table>
			<h3>SALESMAN ADDRESS</h3>
			<div class="mt-3"></div>
			<tr>
				<td>Address :</td>
				<td>
					<input type="text" name="address[address]"></td>
			</tr>
			<tr>
				<td>LastName :</td>
				<td>
					<input type="text" name="address[city]"></td>
			</tr>
			<tr>
				<td>Email :</td>
				<td>
					<input type="text" name="address[state]">	</td>
			</tr>
			<tr>
				<td>Gender :</td>
				<td>
					<input type="text" name="address[country]"	>	</td>
			</tr>
			<tr>
				<td>Mobile :</td>
				<td>
					<input type="text" name="address[zipcode]"></td>
			</tr>
			
		</table>


		
