<?php
echo "<pre>";
$address = $this->getData();
print_r($address);
?>
		<table>
			<h3>SALESMAN ADDRESS</h3>
			<div class="mt-3"></div>
			<tr>
				<td>Address :</td>
				<td>
					<input type="text" name="address[address]" value="<?php echo $address->address ?>"></td>
			</tr>
			<tr>
				<td>City :</td>
				<td>
					<input type="text" name="address[city]" value="<?php echo $address->city ?>"></td>
			</tr>
			<tr>
				<td>Satate :</td>
				<td>
					<input type="text" name="address[state]" value="<?php echo $address->state ?>">	</td>
			</tr>
			<tr>
				<td>Country :</td>
				<td>
					<input type="text" name="address[country]" value="<?php echo $address->country ?>"	>	</td>
			</tr>
			<tr>
				<td>ZipCode :</td>
				<td>
					<input type="text" name="address[zipcode]" value="<?php echo $address->zipcode ?>"></td>
			</tr>
			
		</table>


		
