<?php
$rows = $this->getCollection();
?>
   <div class="row">
      <div class="col-9">
          <h3> <?php echo $this->getTitle() ?></h3>
      </div>
      <div class="col-3">
         <?php foreach ($this->getButtons() as $key => $button) :?>
          <a  class="btn btn-primary" href="<?php echo $button['url'] ?>"><?php echo $button['title']; ?></a>
<?php endforeach;?>
</div>
</div>
<table class="table table-bordered">
    <?php if (!$rows) :?>
      <tr>
         <td colspan="8" align="center"> Row not found.</td>
      </tr>
   <?php else : ?>
      <tr>
         <?php foreach ($this->getColumns() as $key => $column) :?>
           <th> <?php echo $column['title'] ?></th>
        <?php endforeach; ?>
        <?php foreach ($this->getActions() as $key => $action) :?>
            <th><?php echo $action['title'] ?></th>
        <?php endforeach; ?>
      </tr>
      <?php foreach ($rows as $row) :?>
      <tr>
         <?php foreach ($this->getColumns() as $key => $column): ?>
            <td><?php echo $this->getColumnValue($row, $key); ?></td>
         <?php endforeach; ?>

         <?php foreach($this->getActions() as $key => $action): ?>
            <td><a href="<?php $method = $action['method']; echo $this->$method($row , $key); ?>">
               <?php echo $action['title'];?></a></td>
         <?php endforeach; ?>
      </tr>
   <?php endforeach; ?>
    <?php endif; ?>
</table>

